image: maven:3-openjdk-11

stages:
  - build
  - publish

build:
  stage: build
  only:
    - master
  tags:
    - docker
    - linux
  artifacts:
    expire_in: 1d
    paths:
      - build/
  script:
    - mvn clean package -DskipTests

publish:
  stage: publish
  image: tiangolo/docker-with-compose
  only:
    - master
  tags:
    - docker
    - linux
  script:
    - docker image build . -t registry:5000/lottery-api:latest
    - docker image push registry:5000/lottery-api:latest
