image: maven:3-openjdk-11

stages:
  - build
  - publish

build:
  stage: build
  only:
    - master
  tags:
    - docker
    - linux
  artifacts:
    expire_in: 1 day
    paths:
      - target/
  script:
    - mvn clean package -DskipTests

publish:
  stage: publish
  image: tiangolo/docker-with-compose
  only:
    - master
  tags:
    - docker
    - linux
  script:
    - echo $CI_DEPLOY_USER
    - echo $CI_DEPLOY_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker image build . -t gitlab.com/claranet-red/java-api-test:latest
    - docker image push gitlab.com/claranet-red/java-api-test:latest
