image: maven:3-openjdk-11

stages:
  - build
  - publish

build:
  stage: build
  only:
    - master
  tags:
    - docker
    - linux
  artifacts:
    expire_in: 1 day
    paths:
      - target/
  script:
    - mvn clean package -DskipTests

publish:
  stage: publish
  image: docker:latest
  only:
    - master
  tags:
    - docker
    - linux
  script:
    - IMAGE_NAME=$CI_REGISTRY/claranet-red/java-api-test/lottery-api:latest
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker image build . -t $IMAGE_NAME
    - docker image push $IMAGE_NAME
