image: maven:3-openjdk-11

stages:
  - publish

publish:
  stage: publish
  only:
    - master
  tags:
    - docker
    - linux
  script:
    - mvn clean package -DskipTests
    - docker image build . -t registry:5000/lottery-api:latest
    - docker image push registry:5000/lottery-api:latest
